1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]

3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

İki boyutlu arraydaki 2 elemanına ulaşalım.

İki boyutlu arraydaki 7 elemanına ulaşalım.

Üç boyutlu arraydaki 9 elemanına ulaşalım.

Üç boyutlu arraydaki 5 elemanına ulaşalım.

4. Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.



In [ ]:
import numpy as np

# 1. Bir boyutlu integer array oluştur
array1 = np.array([1, 3, 5, 7], dtype=int)
print("1D Array:", array1)
print("Boyut:", array1.ndim)
print("Eleman sayısı:", array1.size)
print("Shape:", array1.shape)

# 2. İki boyutlu array oluştur
array2 = np.array([[1, 2, 6, 7], [4, 3, 9, 5]])
print("\n2D Array:\n", array2)
print("Boyut:", array2.ndim)
print("Eleman sayısı:", array2.size)
print("Shape:", array2.shape)

# 3. Üç boyutlu array oluştur
array3 = np.array([
    [[7, 5, 14], [21, 8, 11]],
    [[8, 6, 20], [14, 3, 9]]
])
print("\n3D Array:\n", array3)
print("Boyut:", array3.ndim)
print("Eleman sayısı:", array3.size)
print("Shape:", array3.shape)

# 4. Indexleme işlemleri
print("\nIndexleme:")
print("2D array -> 2:", array2[0][1])
print("2D array -> 7:", array2[0][3])
print("3D array -> 9:", array3[1][1][2])
print("3D array -> 5:", array3[0][0][1])

# 5. Slicing işlemleri
print("\nSlicing:")
print("2D array -> 2,6:", array2[0][1:3])
print("2D array -> 3,9,5:", array2[1][1:])
print("3D array -> 21,8,11:", array3[0][1])
print("3D array -> 6,20:", array3[1][0][1:3])

# 6. 5x3'lük sıfır ve birlerden oluşan array'ler oluştur
a = np.zeros((5, 3), dtype=int)
b = np.ones((5, 3), dtype=int)
print("\nZeros Array:\n", a)
print("Ones Array:\n", b)

# Satır bazında birleştirme (alt alta)
birlesim_satir = np.concatenate((a, b), axis=0)
print("\nSatır Bazında Birleşim:\n", birlesim_satir)

# Sütun bazında birleştirme (yan yana)
birlesim_sutun = np.concatenate((a, b), axis=1)
print("\nSütun Bazında Birleşim:\n", birlesim_sutun)


1D Array: [1 3 5 7]
Boyut: 1
Eleman sayısı: 4
Shape: (4,)

2D Array:
 [[1 2 6 7]
 [4 3 9 5]]
Boyut: 2
Eleman sayısı: 8
Shape: (2, 4)

3D Array:
 [[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut: 3
Eleman sayısı: 12
Shape: (2, 2, 3)

Indexleme:
2D array -> 2: 2
2D array -> 7: 7
3D array -> 9: 9
3D array -> 5: 5

Slicing:
2D array -> 2,6: [2 6]
2D array -> 3,9,5: [3 9 5]
3D array -> 21,8,11: [21  8 11]
3D array -> 6,20: [ 6 20]

Zeros Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Ones Array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Satır Bazında Birleşim:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sütun Bazında Birleşim:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
